---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: spring-demo-event
spec:
  broker: default
  filter:
    attributes:
      type: com.example.springevent
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: spring-demo
    uri: event
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: spring-demo-news
spec:
  broker: default
  filter:
    attributes:
      type: com.example.springnews
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: spring-demo
    uri: news
