apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: spring-demo
build:
  local:
    push: true
  artifacts:
    - image: spring-demo
      buildpacks:
        builder: 'paketobuildpacks/builder:bionic'
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - knative-service.yaml
    - knative-trigger.yaml
